edition = "2024"
fn_params_layout = "Compressed"
hard_tabs = true
#indent_style = "Block"
match_block_trailing_comma = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 8
use_field_init_shorthand = true
use_try_shorthand = false
