[lamp]
ip = "127.0.0.1:1234"
default-duration = "500ms"
read-timeout = "1500ms"
write-timeout = ""
connection-tries = 5
connection-tries-wait = "1.5s"
connection-timeout = "5s"

[mqtt]
ip = "127.0.0.1:1111"
client-id = "yeerugina-example"
topic = "foobar"
sub-id = 32
qos = 2
lwt-payload = "goodbye"
